import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Program } from '../models/program';

@Injectable({
  providedIn: 'root',
})
export class ProgramService {
  private programs: Program[] = [
    {
      id: '1',
      title: 'Illustration Design',
      university: 'European Institute of Paris',
      country: 'Spain',
      flag: 'https://flagcdn.com/es.svg',
      image: 'assets/Images/userImg2.jpeg',
      price: 45000,
      duration: '4 years',
      level: 'Undergraduate',
      type: 'Full Time',
      attendance: 'E-Learning',
      startDate: '18th June 2023',
      isFavorite: false,
      verifiedIcon: 'assets/verified.png',
      schoolIcon: 'assets/schoolIcon.png',
      countryFlags: [
        { flag: 'https://flagcdn.com/es.svg', code: 'ESP' },
        { flag: 'https://flagcdn.com/de.svg', code: 'GER' },
        { flag: 'https://flagcdn.com/ng.svg', code: 'NGA' },
      ],
      startDateColor: 'bg-success',
      attendanceColor: 'bg-primary',
    },
    {
      id: '2',
      title: 'Illustration Design',
      university: 'European Institute of Paris',
      country: 'Spain',
      flag: 'https://flagcdn.com/es.svg',
      image: 'assets/Images/userImg1.jpeg',
      price: 45000,
      duration: '4 years',
      level: 'Undergraduate',
      type: 'Full Time',
      attendance: 'E-Learning',
      startDate: '18th June 2023',
      isFavorite: false,
      verifiedIcon: 'assets/verified.png',
      schoolIcon: 'assets/schoolIcon.png',
      countryFlags: [
        { flag: 'https://flagcdn.com/es.svg', code: 'ESP' },
        { flag: 'https://flagcdn.com/de.svg', code: 'GER' },
        { flag: 'https://flagcdn.com/ng.svg', code: 'NGA' },
      ],
      startDateColor: 'bg-warning',
      attendanceColor: 'bg-danger',
    },
    {
      id: '3',
      title: 'Experiencing Design: Deepening Your Design Thinking Practice',
      university: 'Harvard University',
      country: 'United States',
      flag: 'https://flagcdn.com/us.svg',
      image: 'assets/Images/userImg2.jpeg',
      price: 10500,
      duration: '2 years',
      level: 'Masters',
      type: 'Part Time',
      attendance: 'Hybrid',
      startDate: '28th Dec 2022',
      isFavorite: true,
      verifiedIcon: 'assets/verified.png',
      schoolIcon: 'assets/schoolIcon.png',
      countryFlags: [
        { flag: 'https://flagcdn.com/gb-eng.svg', code: 'ENG' },
        { flag: 'https://flagcdn.com/de.svg', code: 'GER' },
        { flag: 'https://flagcdn.com/us.svg', code: 'USA' },
      ],
      startDateColor: 'bg-success',
      attendanceColor: 'bg-primary',
    },
    {
      id: '4',
      title: 'Designing for Accessibility',
      university: 'University of Boston',
      country: 'Nigeria',
      flag: 'https://flagcdn.com/ng.svg',
      image: 'assets/Images/userImg1.jpeg',
      price: 5000,
      duration: '2 years',
      level: 'Masters',
      type: 'Part Time',
      attendance: 'Hybrid',
      startDate: '28th Dec 2022',
      isFavorite: false,
      verifiedIcon: 'assets/verified.png',
      schoolIcon: 'assets/schoolIcon.png',
      countryFlags: [
        { flag: 'https://flagcdn.com/ng.svg', code: 'NGA' },
      ],
      startDateColor: 'bg-success',
      attendanceColor: 'bg-warning',
    },
    {
      id: '5',
      title: 'Illustration Design',
      university: 'European Institute of Paris',
      country: 'Spain',
      flag: 'https://flagcdn.com/es.svg',
      image: 'assets/Images/userImg1.jpeg',
      price: 45000,
      duration: '4 years',
      level: 'Undergraduate',
      type: 'Full Time',
      attendance: 'E-Learning',
      startDate: '18th June 2023',
      isFavorite: false,
      verifiedIcon: 'assets/verified.png',
      schoolIcon: 'assets/schoolIcon.png',
      countryFlags: [
        { flag: 'https://flagcdn.com/es.svg', code: 'ESP' },
        { flag: 'https://flagcdn.com/de.svg', code: 'GER' },
        { flag: 'https://flagcdn.com/ng.svg', code: 'NGA' },
      ],
      startDateColor: 'bg-success',
      attendanceColor: 'bg-primary',
    },
    {
      id: '6',
      title: 'Experiencing Design: Deepening Your Design Thinking Practice',
      university: 'Harvard University',
      country: 'United States',
      flag: 'https://flagcdn.com/us.svg',
      image: 'assets/Images/userImg2.jpeg',
      price: 10500,
      duration: '2 years',
      level: 'Masters',
      type: 'Part Time',
      attendance: 'Hybrid',
      startDate: '28th Dec 2022',
      isFavorite: true,
      verifiedIcon: 'assets/verified.png',
      schoolIcon: 'assets/schoolIcon.png',
      countryFlags: [
        { flag: 'https://flagcdn.com/us.svg', code: 'USA' },
        { flag: 'https://flagcdn.com/de.svg', code: 'GER' },
        { flag: 'https://flagcdn.com/ng.svg', code: 'NGA' },
      ],
      startDateColor: 'bg-success',
      attendanceColor: 'bg-primary',
    },
    {
      id: '7',
      title: 'Illustration Design',
      university: 'European Institute of Paris',
      country: 'Canada',
      flag: 'https://flagcdn.com/au.svg',
      image: 'assets/Images/userImg1.jpeg',
      price: 45000,
      duration: '4 years',
      level: 'Undergraduate',
      type: 'Full Time',
      attendance: 'E-Learning',
      startDate: '18th June 2023',
      isFavorite: false,
      verifiedIcon: 'assets/verified.png',
      schoolIcon: 'assets/schoolIcon.png',
      countryFlags: [
        { flag: 'https://flagcdn.com/au.svg', code: 'ENG' },
        { flag: 'https://flagcdn.com/de.svg', code: 'GER' },
        { flag: 'https://flagcdn.com/ng.svg', code: 'NGA' },
      ],
      startDateColor: 'bg-danger',
      attendanceColor: 'bg-success',
    },
    {
      id: '8',
      title: 'Designing for Accessibility',
      university: 'University of Boston',
      country: 'Nigeria',
      flag: 'https://flagcdn.com/ng.svg',
      image: 'assets/Images/userImg1.jpeg',
      price: 5000,
      duration: '2 years',
      level: 'Masters',
      type: 'Part Time',
      attendance: 'Hybrid',
      startDate: '28th Dec 2022',
      isFavorite: false,
      verifiedIcon: 'assets/verified.png',
      schoolIcon: 'assets/schoolIcon.png',
      countryFlags: [
        { flag: 'https://flagcdn.com/gb-eng.svg', code: 'ENG' },
        { flag: 'https://flagcdn.com/de.svg', code: 'GER' },
        { flag: 'https://flagcdn.com/ng.svg', code: 'NGA' },
      ],
      startDateColor: 'bg-danger',
      attendanceColor: 'bg-success',
    },
    {
      id: '9',
      title: 'Illustration Design',
      university: 'European Institute of Paris',
      country: 'Spain',
      flag: 'https://flagcdn.com/es.svg',
      image: 'assets/Images/userImg2.jpeg',
      price: 45000,
      duration: '4 years',
      level: 'Undergraduate',
      type: 'Full Time',
      attendance: 'E-Learning',
      startDate: '18th June 2023',
      isFavorite: false,
      verifiedIcon: 'assets/verified.png',
      schoolIcon: 'assets/schoolIcon.png',
      countryFlags: [
        { flag: 'https://flagcdn.com/es.svg', code: 'ESP' },
      ],
      startDateColor: 'bg-danger',
      attendanceColor: 'bg-success',
    },
  ];

  constructor() {}

  getPrograms(): Observable<Program[]> {
    return of(this.programs);
  }

  getProgram(id: string): Observable<Program | undefined> {
    return of(this.programs.find((program) => program.id === id));
  }

  toggleFavorite(id: string): void {
    const program = this.programs.find((p) => p.id === id);
    if (program) {
      program.isFavorite = !program.isFavorite;
    }
  }
}
